services:
  chqe-debug-node:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROFILE: debug
    ports:
      - "7000:7000"
  chqe-release-node:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROFILE: release
    ports:
      - "7000:7000"

